name: e_commerce_fitmode
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  buttons_tabbar: ^1.3.14
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.7.0
  either_dart: ^1.0.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  fluentui_system_icons: ^1.1.270
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_paypal_payment: ^1.0.8
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.16
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  linear_progress_bar: ^1.1.3
  lottie: ^3.1.3
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icons/
    - assets/images/
