// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWLbK2TGuPU7hHFpYtvyCPEloCBqFyYik',
    appId: '1:23031447424:android:5e9d7cdd41855e4ee7cb65',
    messagingSenderId: '23031447424',
    projectId: 'furniture-1f40c',
    storageBucket: 'furniture-1f40c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMlZnhNaf1sJXvAHf9Q2wjP7N88vOq_xE',
    appId: '1:23031447424:ios:57a32540be4f34f8e7cb65',
    messagingSenderId: '23031447424',
    projectId: 'furniture-1f40c',
    storageBucket: 'furniture-1f40c.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFitmode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV8pOJlXIUY9OqKSgU5934z4CL-bKXung',
    appId: '1:23031447424:web:a6567d0d2c1ab977e7cb65',
    messagingSenderId: '23031447424',
    projectId: 'furniture-1f40c',
    authDomain: 'furniture-1f40c.firebaseapp.com',
    storageBucket: 'furniture-1f40c.firebasestorage.app',
    measurementId: 'G-SMDP77KFYZ',
  );
}
